/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

/**
 *
 * @author USER
 */
public class principal_page extends javax.swing.JFrame {

    /**
     * Creates new form principal_page
     */
    public principal_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblTelNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblAddress = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblAge = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblGender = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jbtnChange = new javax.swing.JButton();
        jbtnHomePage = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Principal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profi_image.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jlblTelNo.setBackground(new java.awt.Color(255, 255, 255));
        jlblTelNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblTelNo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlblTelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 210, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jlblID.setBackground(new java.awt.Color(255, 255, 255));
        jlblID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 210, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jlblAddress.setBackground(new java.awt.Color(255, 255, 255));
        jlblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblAddress.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 210, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Age");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jlblAge.setBackground(new java.awt.Color(255, 255, 255));
        jlblAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblAge.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, 20));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jlblGender.setBackground(new java.awt.Color(255, 255, 255));
        jlblGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblGender.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 210, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tel No");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jlblName.setBackground(new java.awt.Color(255, 255, 255));
        jlblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 210, 30));

        jbtnChange.setBackground(new java.awt.Color(255, 255, 255));
        jbtnChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnChange.setForeground(new java.awt.Color(0, 0, 0));
        jbtnChange.setText("Change");
        jbtnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 110, -1));

        jbtnHomePage.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHomePage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnHomePage.setForeground(new java.awt.Color(0, 0, 0));
        jbtnHomePage.setText("Home Page");
        jbtnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomePageActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jbtnCancel.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCancel.setForeground(new java.awt.Color(0, 0, 0));
        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomePageActionPerformed
        home_page home = new home_page();
        home.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jbtnHomePageActionPerformed

    private void jbtnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeActionPerformed
        principal_Profile_page principal1 = new principal_Profile_page();
        principal1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jbtnChangeActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnChange;
    private javax.swing.JButton jbtnHomePage;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblAge;
    private javax.swing.JLabel jlblGender;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblTelNo;
    // End of variables declaration//GEN-END:variables
}
